fix: JSエラー修正

diff --git a/.github/workflows/rspec.yml b/.github/workflows/rspec.yml
--- a/.github/workflows/rspec.yml
+++ b/.github/workflows/rspec.yml
@@ -50,7 +50,11 @@ jobs:
           docker compose -f compose.ci.yml exec -T -w /rails web bash -c "bundle install && bundle exec rails db:prepare"
 
           echo "Precompiling assets (Skip JS build if fails)..."
-          docker compose -f compose.ci.yml exec -T -w /rails web bash -c "mkdir -p app/assets/builds && touch app/assets/builds/application.css && bundle exec rails assets:precompile" || echo "Assets precompile failed but continuing..."
+          docker compose -f compose.ci.yml exec -T -w /rails web bash -c "
+            mkdir -p app/assets/builds && 
+            touch app/assets/builds/application.css && 
+            touch app/assets/builds/application.js && 
+            bundle exec rails assets:precompile" || echo "Assets precompile failed but continuing..."
 
           echo "Running RSpec..."
           docker compose -f compose.ci.yml exec -T -w /rails web bundle exec rspec
